# Generated by Django 4.2.5 on 2023-09-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.CharField(default='Mammalia', max_length=255),
        ),
        migrations.AddField(
            model_name='animal',
            name='family',
            field=models.CharField(default='Mammalia', max_length=255),
            preserve_default=False,
        ),
    ]
