# Generated by Django 4.2.5 on 2023-09-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_animal_category_animal_animal_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
