# Generated by Django 4.2.5 on 2023-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_animal_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
